scrape_configs:
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - http://connectivitycheck.hk.yzi.io/generate_204    # Target to probe with http.
        - http://connectivitycheck.platform.hicloud.com/generate_204    # Target to probe with http.
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: black-exporter:9115  # The blackbox exporter's real hostname:port.