{
 "title": "HAProxy Server",
 "description": "This dashboard displays the detailed HAProxy information of sections and backend servers.",
 "tags": [
  "haproxy",
  "prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "10s,1m,5m,1h,6h,1d" },
   {
    "name": "service_name",
    "label": "HAProxy Instance",
    "query": "label_values(haproxy_up, service_name)"
   },
   {
    "name": "backend",
    "label": "Backend",
    "query": "label_values(haproxy_backend_bytes_in_total{service_name=\"$service_name\"}, backend)"
   },
   {
    "name": "frontend",
    "label": "Frontend",
    "query": "label_values(haproxy_frontend_bytes_in_total{service_name=~\"$service_name\"}, frontend)"
   }
  ]
 },
 "panels": [
  {
   "title": "Incoming Data by Servers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg by (service_name,backend,server) (rate(haproxy_server_bytes_in_total{backend=~\"$backend\",service_name=~\"$service_name\"}[$interval]) or irate(haproxy_server_bytes_in_total{backend=~\"$backend\",service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "{{backend}} - {{server}}"
    }
   ]
  },
  {
   "title": "Outgoing Data by Servers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg by (service_name,backend,server) (rate(haproxy_server_bytes_out_total{backend=~\"$backend\",service_name=~\"$service_name\"}[$interval]) or irate(haproxy_server_bytes_out_total{backend=~\"$backend\",service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "{{backend}} - {{server}}"
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (service_name,backend,server) (rate(haproxy_server_sessions_total{service_name=~\"$service_name\",backend=~\"$backend\"}[$interval]) or irate(haproxy_server_sessions_total{service_name=~\"$service_name\",backend=~\"$backend\"}[5m]))",
     "legendFormat": "{{backend}} - {{server}}"
    }
   ]
  },
  {
   "title": "Health Check Duration",
   "type": "graph",
   "description": "Previously run health check duration, in seconds",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg by (service_name,backend,server) (max_over_time(haproxy_server_check_duration_seconds{service_name=~\"$service_name\",backend=~\"$backend\"}[$interval]) or max_over_time(haproxy_server_check_duration_seconds{service_name=~\"$service_name\",backend=~\"$backend\"}[5m]))",
     "legendFormat": "{{backend}} - {{server}}"
    }
   ]
  },
  {
   "title": "Failed Health Checks",
   "type": "graph",
   "description": "Total number of failed health checks.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg by (service_name,backend,server) (rate(haproxy_server_check_failures_total{backend=~\"$backend\",service_name=~\"$service_name\"}[$interval]) or irate(haproxy_server_check_failures_total{backend=~\"$backend\",service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "{{backend}} - {{server}}"
    }
   ]
  },
  {
   "title": "Retry Warnings",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg by (service_name,backend,server) (rate(haproxy_server_retry_warnings_total{backend=~\"$backend\",service_name=~\"$service_name\"}[$interval]) or irate(haproxy_server_retry_warnings_total{backend=~\"$backend\",service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "{{backend}} - {{server}}"
    }
   ]
  },
  {
   "title": "Downtime",
   "type": "graph",
   "description": "Total downtime in seconds.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg by (service_name,backend,server) (rate(haproxy_server_downtime_seconds_total{backend=~\"$backend\",service_name=~\"$service_name\"}[$interval]) or irate(haproxy_server_downtime_seconds_total{backend=~\"$backend\",service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "{{backend}} - {{server}}"
    }
   ]
  },
  {
   "title": "Active Sessions",
   "type": "graph",
   "description": "Current number of active sessions.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg by (service_name,backend,server) (max_over_time(haproxy_server_current_sessions{backend=~\"$backend\",service_name=~\"$service_name\"}[$interval]) or max_over_time(haproxy_server_current_sessions{backend=~\"$backend\",service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "{{backend}} - {{server}}"
    }
   ]
  }
 ]
}