{
 "title": "HAProxy Server",
 "description": "HAProxy with Prometheus data",
 "tags": [
  "haproxy",
  "servers"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(haproxy_process_nbproc,instance)"
   },
   {
    "name": "port",
    "query": "label_values(haproxy_process_nbproc, instance)"
   },
   {
    "name": "backend",
    "label": "Backend",
    "query": "label_values(haproxy_backend_status{instance=~\"$host:$port\"}, proxy)"
   },
   {
    "name": "frontend",
    "label": "Frontend",
    "query": "label_values(haproxy_frontend_status{instance=~\"$host:$port\"}, proxy)"
   },
   {
    "name": "server",
    "label": "Server",
    "query": "label_values(haproxy_server_status{instance=~\"$host:$port\"}, server)"
   },
   {
    "name": "code",
    "label": "HTTP Code",
    "query": "label_values(haproxy_server_http_responses_total{instance=~\"$host:$port\"}, code)"
   },
   { "name": "interval", "label": "Interval", "query": "30s,1m,5m,1h,6h,1d" }
  ]
 },
 "panels": [
  { "title": "By server - Health and Weight", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Server - Service weight",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "none", "label": "weight" }
   ],
   "targets": [
    {
     "expr": "haproxy_server_weight{proxy=~\"$backend\",server=~\"$server\",instance=~\"$host:$port\"}",
     "legendFormat": "{{ proxy }} / {{ server }}"
    }
   ]
  },
  {
   "title": "Server - UP->DOWN transitions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none", "label": "transitions" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_server_check_up_down_total{proxy=~\"$backend\",server=~\"$server\",instance=~\"$host:$port\"}[5m])",
     "legendFormat": "{{ proxy }} / {{ server }}"
    }
   ]
  },
  {
   "title": "Server - Checks failures",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "none", "label": "failures" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_server_check_failures_total{proxy=~\"$backend\",server=~\"$server\",instance=~\"$host:$port\"}[5m])",
     "legendFormat": "{{ proxy }} / {{ server }}"
    }
   ]
  },
  {
   "title": "Server - Checks duration",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "haproxy_server_check_duration_seconds{proxy=~\"$backend\",server=~\"$server\",instance=~\"$host:$port\"}",
     "legendFormat": "{{ proxy }} / {{ server }}"
    }
   ]
  },
  {
   "title": "Server -Throttle percentage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "haproxy_server_current_throttle{proxy=~\"$backend\",server=~\"$server\",instance=~\"$host:$port\"}",
     "legendFormat": "{{ proxy }} / {{ server }}"
    }
   ]
  },
  {
   "title": "Server - Number of seconds since last session assigned to server/backend",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_server_last_session_seconds{proxy=~\"$backend\", server=~\"$server\",instance=~\"$host:$port\"}[5m])",
     "legendFormat": "{{ proxy }} / {{ server }}"
    }
   ]
  },
  {
   "title": "By server - Throughtput  / Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 },
   "collapsed": true,
   "panels": [
    {
     "title": "Server - Incoming / Outgoing bytes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "bits", "label": "- out / + in" }
     ],
     "targets": [
      {
       "expr": "irate(haproxy_server_bytes_in_total{proxy=~\"$backend\",server=~\"$server\",instance=~\"$host:$port\"}[5m])*8",
       "legendFormat": "IN {{ proxy }} / {{ server }}"
      },
      {
       "expr": "irate(haproxy_server_bytes_out_total{proxy=~\"$backend\",server=~\"$server\",instance=~\"$host:$port\"}[5m])*8",
       "legendFormat": "OUT {{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Connections attempts / error",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short", "label": "- error / + attempts" }
     ],
     "targets": [
      {
       "expr": "irate(haproxy_server_connection_attempts_total{proxy=~\"$backend\",server=~\"$server\",instance=~\"$host:$port\"}[5m])",
       "legendFormat": "Attempts {{ proxy }} / {{ server }}"
      },
      {
       "expr": "irate(haproxy_server_connection_errors_total{proxy=~\"$backend\",server=~\"$server\",instance=~\"$host:$port\"}[5m])",
       "legendFormat": "Error {{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Number of connections reuses",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short", "label": "reuses" }
     ],
     "targets": [
      {
       "expr": "irate(haproxy_server_connection_reuses_total{proxy=~\"$backend\",server=~\"$server\",instance=~\"$host:$port\"}[5m])",
       "legendFormat": "Reuses {{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Idle connections",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short", "label": "counter" }
     ],
     "targets": [
      {
       "expr": "irate(haproxy_server_server_idle_connections_current{proxy=~\"$backend\",server=~\"$server\",instance=~\"$host:$port\"}[5m])",
       "legendFormat": "Available idle connections {{ proxy }} / {{ server }}"
      },
      {
       "expr": "irate(haproxy_server_server_idle_connections_limit{proxy=~\"$backend\",server=~\"$server\",instance=~\"$host:$port\"}[5m])",
       "legendFormat": "Limit available idle connections {{ proxy }} / {{ server }}{{ proxy }}"
      }
     ]
    }
   ]
  },
  {
   "title": "By server - Requests / Responses / Queues",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 },
   "collapsed": true,
   "panels": [
    {
     "title": "Server - HTTP responses denied",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short", "label": "denied" }
     ],
     "targets": [
      {
       "expr": "irate(haproxy_server_responses_denied_total{proxy=~\"$backend\", instance=~\"$host:$port\"}[5m])",
       "legendFormat": "Denied {{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Error / Redispatch / Retry",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short", "label": "- error / + redispatch + retry" }
     ],
     "targets": [
      {
       "expr": "irate(haproxy_server_redispatch_warnings_total{proxy=~\"$backend\",server=~\"$server\",instance=~\"$host:$port\"}[5m])",
       "legendFormat": "Redispatch {{ proxy }} / {{ server }}"
      },
      {
       "expr": "irate(haproxy_server_retry_warnings_total{proxy=~\"$backend\",server=~\"$server\",instance=~\"$host:$port\"}[5m])",
       "legendFormat": "Retry {{ proxy }} / {{ server }}"
      },
      {
       "expr": "irate(haproxy_server_response_errors_total{proxy=~\"$backend\",server=~\"$server\",instance=~\"$host:$port\"}[5m])",
       "legendFormat": "Error {{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Queued requests",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short", "label": "requests" }
     ],
     "targets": [
      {
       "expr": "irate(haproxy_server_current_queue{proxy=~\"$backend\",server=~\"$server\",instance=~\"$host:$port\"}[5m])",
       "legendFormat": "Current {{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Max  queued requests and limit",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short", "label": "requests" }
     ],
     "targets": [
      {
       "expr": "haproxy_server_max_queue{proxy=~\"$backend\",server=~\"$server\",instance=~\"$host:$port\"}",
       "legendFormat": "Max {{ proxy }} / {{ server }}"
      },
      {
       "expr": "haproxy_server_queue_limit{proxy=~\"$backend\",server=~\"$server\",instance=~\"$host:$port\"}",
       "legendFormat": "Limit {{ proxy }} / {{ server }}"
      }
     ]
    }
   ]
  },
  {
   "title": "By server - Times",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 },
   "collapsed": true,
   "panels": [
    {
     "title": "Server - Average connection time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "haproxy_server_connect_time_average_seconds{proxy=~\"$backend\",server=~\"$server\",instance=~\"$host:$port\"}",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Max connection time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "haproxy_server_max_connect_time_seconds{proxy=~\"$backend\",server=~\"$server\",instance=~\"$host:$port\"}",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Average response time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "haproxy_server_response_time_average_seconds{proxy=~\"$backend\",server=~\"$server\",instance=~\"$host:$port\"}",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Max response time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "haproxy_server_max_response_time_seconds{proxy=~\"$backend\",server=~\"$server\",instance=~\"$host:$port\"}",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Average total time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "haproxy_server_total_time_average_seconds{proxy=~\"$backend\",server=~\"$server\",instance=~\"$host:$port\"}",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Max total time",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "haproxy_server_max_total_time_seconds{proxy=~\"$backend\",server=~\"$server\",instance=~\"$host:$port\"}",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Average queue time for last 1024 successful connections",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "irate(haproxy_server_queue_time_average_seconds{proxy=~\"$backend\",server=~\"$server\",instance=~\"$host:$port\"}[5m])",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Max queue time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 57 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "irate(haproxy_server_max_queue_time_seconds{proxy=~\"$backend\",server=~\"$server\",instance=~\"$host:$port\"}[5m])",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    }
   ]
  },
  {
   "title": "By server - Sessions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 },
   "collapsed": true,
   "panels": [
    {
     "title": "Server - Number of active sessions",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(haproxy_server_sessions_total{proxy=~\"$backend\",server=~\"$server\",instance=~\"$host:$port\"}[5m])",
       "legendFormat": "Total {{ proxy }} / {{ server }}"
      },
      {
       "expr": "haproxy_server_limit_sessions{proxy=~\"$backend\",instance=~\"$host:$port\"}",
       "legendFormat": "Limit {{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Failed header rewriting warnings",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(haproxy_server_failed_header_rewriting_total{proxy=~\"$frontend\",server=~\"$server\",instance=~\"$host:$port\"}[5m])",
       "legendFormat": "{{ proxy }} /  {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Number of sessions per second and limit",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "haproxy_server_max_session_rate{proxy=~\"$backend\",server=~\"$server\",instance=~\"$host:$port\"}",
       "legendFormat": "Rate {{ proxy }} / {{ server }}"
      },
      {
       "expr": "haproxy_server_limit_session_rate{proxy=~\"$backend\",server=~\"$server\",instance=~\"$host:$port\"}",
       "legendFormat": "Limit {{ proxy }} / {{ server }}"
      }
     ]
    }
   ]
  },
  {
   "title": "By server - Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 },
   "collapsed": true,
   "panels": [
    {
     "title": "Server - Status",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short", "label": "counter" }
     ],
     "targets": [
      {
       "expr": "haproxy_server_status{proxy=~\"$backend\",server=~\"$server\",instance=~\"$host:$port\"}",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Internal errors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short", "label": "counter" }
     ],
     "targets": [
      {
       "expr": "irate(haproxy_server_internal_errors_total{proxy=~\"$backend\",instance=~\"$host:$port\"}[5m])",
       "legendFormat": "{{ proxy }}"
      }
     ]
    }
   ]
  }
 ]
}