name: CI Aria2

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Aria2 TAG'
        required: true

jobs:
  main:
    runs-on: self-hosted
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.YZI_HUB_USERNAME }}
          password: ${{ secrets.YZI_HUB_TOKEN }}
          registry: ${{ secrets.YZI_HUB }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./aria2
          file: ./aria2/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.YZI_HUB }}/yzi/aria2:${{ github.event.inputs.tag }}